import processes

av = (
    'alunotify',
    'aluschedulersvc',
    'CCAP',
    'ccap',
    'ccapp',
    'ccevtmgr',
    'ccEvtMgr',
    'ccproxy',
    'ccpxysvc',
    'ccSetmgr',
    'ccsetmgr',
    'ccSetMgr',
    'dbserv',
    'djsnetcn',
    'doscan',
    'dwhwizrd',
    'DWHWizrd',
    'ghost_2',
    'icepack',
    'luall',
    'LUALL',
    'lucallbackproxy',
    'lucoms',
    'lucoms~1',
    'ndetect',
    'ngctw32',
    'ngserver',
    'nsctop',
    'NscTop',
    'nsmdtr',
    'NSMdtr',
    'olfsnt40',
    'OLFSNT40',
    'pxemtftp',
    'pxeservice',
    'rtvscan',
    'RTVscan',
    'SAVFMSESp',
    'savroam',
    'SavRoam',
    'scanexplicit',
    'SMSECtrl',
    'SMSELog',
    'SMSESJM',
    'SMSESp',
    'smsesp',
    'SMSESrv',
    'SMSETask',
    'SMSEUI',
    'sndmon',
    'SNDMon',
    'spbbcsvc',
    'SPBBCSvc',
    'SSM',
    'symproxysvc',
    'symsport',
    'SymSPort',
    'symtray',
    'symwsc',
    'UcService',
    'updtnv28',
    'UsrPrmpt',
    'usrprmpt',
    'VPC32',
    'vpc32',
    'wfxctl32',
    'WFXMOD32',
    'wfxsnt40',
    'AluSchedulerSvc',
    'ccApp',
    'ccSvcHst',
    'LUALL',
    'Rtvscan',
    'SavUI',
    'SescLU',
    'Smc',
    'SmcGui',
    'ccLgView',
    'MCUI32',
    'symlcsvc',
    'AppSvc32',
    'ccSvcHst',
)

e = processes.shadowbrokers_executables()

for item in av:
    if item.lower() + '.exe' not in e:
        print(item + '.exe')
